# Generated by Django 5.2.10 on 2026-01-22 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('price', models.IntegerField(verbose_name='Giá (VNĐ)')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('area', models.IntegerField(verbose_name='Diện tích (m2)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Ảnh chính')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category', verbose_name='Loại nhà')),
            ],
        ),
    ]
