# Generated by Django 5.2.10 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Nhà đất bán'), ('rent', 'Nhà đất cho thuê')], default='sale', max_length=10, verbose_name='Hình thức'),
        ),
    ]
