# Generated by Django 5.2.10 on 2026-01-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_category_options_alter_listing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('appointment_date', models.DateField(verbose_name='Ngày xem')),
                ('appointment_time', models.TimeField(verbose_name='Giờ xem')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú của khách')),
                ('agent_note', models.TextField(blank=True, verbose_name='Ghi chú của người đăng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='listings.listing', verbose_name='Tin đăng')),
            ],
            options={
                'verbose_name': 'Lịch hẹn xem nhà',
                'verbose_name_plural': 'Lịch hẹn xem nhà',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
